version: '2.3'
services:

 ##########################################################
  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:3-management-alpine
    volumes:
      - mq_data:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672"
      - "5672:5672" 
    networks:
      - log
    environment:
      RABBITMQ_DEFAULT_USER: logUser
      RABBITMQ_DEFAULT_PASS: logPwd
      RABBITMQ_DEFAULT_VHOST: EnterpriseLog
  ##########################################################
  logstash:
    container_name: LogStash    
    image: docker.elastic.co/logstash/logstash-oss:6.2.2
    volumes:
      - ./product.logstash.conf:/config/product.logstash.conf      
    depends_on:
      - rabbitmq
      - elasticsearch        
    links:
      - rabbitmq:AMQPServer
      - elasticsearch:elasticsearch
    networks:
      - log    
    command: ["-f", "/config/product.logstash.conf"]
  ##########################################################
  elasticsearch:
    container_name: ElasticSearch    
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    environment: 
      - "http.host:0.0.0.0"
      - "transport.host:127.0.0.1"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes: 
      - ./product.elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch_data:/usr/share/elasticsearch/data      
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 5
#      start_period: 30s      
    networks:
      - log
  ##########################################################
  kibana:
    container_name: Kibana    
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    volumes:
      - ./product.kibana.yml:/usr/share/kibana/config/kibana.yml   
    depends_on:
      elasticsearch:
        condition: service_healthy
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5601:5601"
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://localhost:5601/ || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 5
#      start_period: 30s      
    networks:
      - log
  ##########################################################
  metricbeat:
    container_name: metricbeat
    image: docker.elastic.co/beats/metricbeat:6.2.2
    user: root
    volumes:
      - ./product.metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy

    networks:
      - log


volumes:
  mq_data:
  elasticsearch_data:

networks:
  log:
    driver: bridge